import { StyleSheet, Platform, StatusBar } from 'react-native';

// We export this so App.js can see it
export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F8FAFC' },
    masterContainer: { flex: 1, backgroundColor: '#1E3A8A' },
    mainContentContainer: { flex: 1, backgroundColor: '#F8FAFC' },
    loginContainer: { flex: 1, backgroundColor: '#1E3A8A' },
    center: { justifyContent: 'center', alignItems: 'center' },
    header: {
        backgroundColor: '#1E3A8A',
        paddingHorizontal: 16,
        paddingBottom: 16,
        paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 24) + 10 : 60,
    },
    headerContent: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    headerIcon: { backgroundColor: 'rgba(255,255,255,0.1)', padding: 8, borderRadius: 8 },
    headerTitle: { color: 'white', fontSize: 18, fontWeight: 'bold' },
    headerSubtitle: { color: '#93C5FD', fontSize: 12 },
    headerRight: { flexDirection: 'row', gap: 8 },
    navButton: { padding: 8, borderRadius: 8 },
    navButtonActive: { backgroundColor: '#1E40AF' },
    content: { flex: 1 },
    loginContent: { padding: 24, width: '100%' },
    loginHeader: { alignItems: 'center', marginBottom: 30 },
    logoCircle: { width: 80, height: 80, backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 40, alignItems: 'center', justifyContent: 'center', marginBottom: 15 },
    loginTitle: { color: 'white', fontSize: 28, fontWeight: 'bold' },
    loginSubtitle: { color: '#BFDBFE', fontSize: 16 },
    logContainer: { padding: 16, gap: 16 },
    dateNav: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: 'white', padding: 12, borderRadius: 16, borderWidth: 1, borderColor: '#E2E8F0' },
    dateText: { fontSize: 18, fontWeight: 'bold', color: '#1E293B' },
    yearText: { fontSize: 12, color: '#94A3B8' },
    arrowButton: { padding: 10, backgroundColor: '#F1F5F9', borderRadius: 10 },
    statsGrid: { flexDirection: 'row', gap: 12 },
    statCard: { flex: 1, backgroundColor: 'white', padding: 16, borderRadius: 16, borderLeftWidth: 4, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 5, elevation: 2 },
    statLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
    statLabel: { fontSize: 10, fontWeight: 'bold', color: '#94A3B8' },
    statValue: { fontSize: 24, fontWeight: 'bold', color: '#1E293B' },
    statSub: { fontSize: 11, color: '#94A3B8' },
    formCard: { backgroundColor: 'white', borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: '#E2E8F0' },
    formHeader: { flexDirection: 'row', justifyContent: 'space-between', padding: 16, backgroundColor: '#F8FAFC', borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
    formTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    iconBox: { backgroundColor: '#DBEAFE', padding: 4, borderRadius: 6 },
    formTitle: { fontWeight: 'bold', color: '#334155' },
    savingText: { fontSize: 12, color: '#2563EB', fontWeight: 'bold' },
    formBody: { padding: 16, gap: 16 },
    label: { fontSize: 10, fontWeight: 'bold', color: '#94A3B8', marginBottom: 6 },
    input: { backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 10, padding: 12, fontSize: 16, fontWeight: '600', color: '#334155' },
    row: { flexDirection: 'row', gap: 12 },
    col: { flex: 1 },
    inputWithIcon: { flexDirection: 'row', alignItems: 'center', position: 'relative' },
    prefix: { position: 'absolute', left: 12, zIndex: 1, fontSize: 16, fontWeight: 'bold', color: '#94A3B8' },
    inputIcon: { position: 'absolute', left: 12, zIndex: 1 },
    pickerScroll: { flexDirection: 'row' },
    chip: { paddingHorizontal: 16, paddingVertical: 8, backgroundColor: '#F1F5F9', borderRadius: 20, marginRight: 8, borderWidth: 1, borderColor: '#E2E8F0' },
    chipActive: { backgroundColor: '#EFF6FF', borderColor: '#3B82F6' },
    chipText: { fontSize: 14, color: '#64748B', fontWeight: '500' },
    chipTextActive: { color: '#2563EB' },
    actionButtons: { gap: 10, marginTop: 10 },
    skipButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, padding: 12, borderRadius: 12, borderWidth: 2, borderColor: '#E2E8F0' },
    skipButtonText: { fontWeight: 'bold', color: '#64748B' },
    saveButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, padding: 12, borderRadius: 12, backgroundColor: '#1E40AF', borderWidth: 2, borderColor: '#1E40AF' },
    saveButtonText: { fontWeight: 'bold', color: 'white' },
    historyCard: { backgroundColor: 'white', borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: '#E2E8F0' },
    historyHeader: { flexDirection: 'row', gap: 8, padding: 12, backgroundColor: '#FEF3C7', alignItems: 'center' },
    historyTitle: { fontSize: 13, fontWeight: 'bold', color: '#92400E' },
    historyWeekContainer: { flexDirection: 'row', justifyContent: 'space-between', padding: 12, borderBottomWidth: 1, borderBottomColor: '#F1F5F9', backgroundColor: '#FFFBEB' },
    historyDayBtn: { alignItems: 'center', padding: 8, borderRadius: 8, minWidth: 44 },
    historyDayBtnActive: { backgroundColor: '#F59E0B' },
    historyDayText: { fontSize: 11, color: '#92400E', fontWeight: 'bold' },
    historyDateText: { fontSize: 16, color: '#92400E', fontWeight: 'bold' },
    historyDayTextActive: { color: 'white' },
    historyDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: '#D97706', marginTop: 4 },
    historyListContainer: { paddingBottom: 10 },
    historySubHeader: { padding: 12, fontSize: 12, fontWeight: 'bold', color: '#94A3B8', textTransform: 'uppercase' },
    historyRow: { padding: 12, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
    historyYear: { fontSize: 12, fontWeight: 'bold', color: '#94A3B8', marginBottom: 2 },
    historyLbsLarge: { fontSize: 22, fontWeight: '900', color: '#1E293B', lineHeight: 28 },
    historyPriceLarge: { fontSize: 17, fontWeight: 'bold', color: '#059669' },
    historyDetailsLarge: { fontSize: 13, fontWeight: '600', color: '#475569', lineHeight: 20 },
    historyNoteContainer: { marginTop: 8, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#E2E8F0' },
    historyNoteText: { fontSize: 13, fontStyle: 'italic', color: '#64748B' },
    noHistoryText: { padding: 20, textAlign: 'center', color: '#94A3B8', fontStyle: 'italic', fontSize: 14 },
    settingsContainer: { padding: 16, gap: 16 },
    card: { backgroundColor: 'white', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 16 },
    cardTitle: { fontSize: 20, fontWeight: 'bold', color: '#1E293B', marginBottom: 20, textAlign: 'center' },
    cardHeader: { fontSize: 16, fontWeight: 'bold', color: '#334155', marginBottom: 16, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
    inputGroup: { marginBottom: 15 },
    inputWrapper: { position: 'relative', justifyContent: 'center' },
    primaryButton: { backgroundColor: '#1E40AF', padding: 16, borderRadius: 12, alignItems: 'center', marginTop: 10 },
    primaryButtonText: { color: 'white', fontWeight: 'bold', fontSize: 16 },
    switchButton: { padding: 10, alignItems: 'center', marginTop: 10 },
    switchButtonText: { color: '#64748B', fontWeight: '500' },
    copyright: { color: '#93C5FD', textAlign: 'center', marginTop: 30, fontSize: 12 },
    outlineButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, padding: 12, borderRadius: 10, borderWidth: 1, borderColor: '#CBD5E1' },
    outlineButtonText: { fontWeight: 'bold', color: '#475569' },
    deleteButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, padding: 12, borderRadius: 10, borderWidth: 1, borderColor: '#FECACA', backgroundColor: '#FEF2F2', marginTop: 12 },
    deleteButtonText: { fontWeight: 'bold', color: '#EF4444' },
    graphHeader: { padding: 16, backgroundColor: '#F8FAFC', borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
    yearNav: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
    graphTitle: { fontSize: 14, fontWeight: 'bold', color: '#1E293B' },
    iconButton: { padding: 4 },
    statsRow: { flexDirection: 'row', justifyContent: 'space-around' },
    statBadge: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    dot: { width: 8, height: 8, borderRadius: 4 },
    statText: { fontSize: 12, fontWeight: 'bold', color: '#64748B' },
    emptyGraph: { padding: 40, alignItems: 'center' },
    emptyGraphText: { color: '#94A3B8' },
    proContainer: { flex: 1, backgroundColor: '#1E293B' },
    proBanner: { alignItems: 'center', justifyContent: 'center', padding: 40, marginTop: 40 },
    proTitle: { fontSize: 24, fontWeight: 'bold', color: 'white', marginTop: 10 },
    proHeader: { padding: 20, backgroundColor: '#0F172A' },
    proLocation: { color: '#94A3B8', fontSize: 12, fontWeight: 'bold', textTransform: 'uppercase' },
    proTime: { color: 'white', fontSize: 32, fontWeight: '300' },
    weatherGrid: { flexDirection: 'row', flexWrap: 'wrap', padding: 10 },
    weatherCard: { width: '45%', backgroundColor: '#334155', borderRadius: 16, padding: 16, margin: '2.5%', alignItems: 'center' },
    weatherIconBox: { backgroundColor: 'rgba(255,255,255,0.1)', padding: 10, borderRadius: 50, marginBottom: 10 },
    weatherLabel: { color: '#94A3B8', fontSize: 10, fontWeight: 'bold', marginBottom: 4 },
    weatherValue: { color: 'white', fontSize: 20, fontWeight: 'bold' },
    weatherSub: { color: '#94A3B8', fontSize: 12 },
    comingSoonCard: { margin: 20, padding: 20, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 16, borderWidth: 1, borderColor: '#334155' },
    comingSoonTitle: { color: '#94A3B8', fontWeight: 'bold', marginBottom: 15, textTransform: 'uppercase', fontSize: 12 },
    featureRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
    featureText: { color: '#CBD5E1' },
    sectionContainer: { marginTop: 20, paddingHorizontal: 16 },
    sectionTitle: { color: '#94A3B8', fontWeight: 'bold', textTransform: 'uppercase', fontSize: 12, marginBottom: 10 },
    tideRow: { flexDirection: 'row', justifyContent: 'space-between', padding: 12, backgroundColor: '#334155', marginBottom: 8, borderRadius: 10 },
    tideType: { color: 'white', fontWeight: 'bold', fontSize: 14 },
    tideTime: { color: '#CBD5E1', fontSize: 14 },
    tideHeight: { color: '#FBBF24', fontWeight: 'bold', fontSize: 14 },
    forecastCard: { backgroundColor: '#334155', padding: 12, borderRadius: 12, marginRight: 10, minWidth: 90, alignItems: 'center' },
    forecastTime: { color: 'white', fontWeight: 'bold', fontSize: 12, marginBottom: 6 },
    forecastDivider: { width: '100%', height: 1, backgroundColor: '#475569', marginBottom: 6 },
    forecastRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 4 },
    forecastValue: { color: 'white', fontWeight: 'bold', fontSize: 12 },
    forecastUnit: { color: '#94A3B8', fontSize: 10 },
    longRangeRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#334155', padding: 16, marginBottom: 8, borderRadius: 12 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', alignItems: 'center' },
    modalContent: { width: '85%', backgroundColor: '#1E293B', borderRadius: 20, padding: 20, borderWidth: 1, borderColor: '#334155' },
    modalTitle: { fontSize: 20, fontWeight: 'bold', color: 'white', marginBottom: 5 },
    modalSubtitle: { color: '#94A3B8', marginBottom: 20 },
    inputLabel: { color: '#94A3B8', fontSize: 10, fontWeight: 'bold', marginBottom: 5, marginTop: 10 },
    modalInput: { backgroundColor: '#0F172A', color: 'white', padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#334155', fontSize: 16 },
    modalButtons: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 25 },
    cancelButton: { padding: 12 },
    modalSaveButton: {
        backgroundColor: '#FBBF24',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 8
    },
});